### ISSUE TITLE
Respect Multi-line comments

### ISSUE THREAD

**Issue by aneilbaboo** [chfritz/atom-sane-indentation#10]
It be nice if sane-indentation respected the format of JSDoc comment blocks.  Not the most burning issue in the world, but if it were fixed, I could trust sane-indentation to correctly format a whole file at a time.  As it is now, I have to carefully pick and choose which blocks I want to auto-indent.

![](http://g.recordit.co/MR0ruDsolx.gif)

**Comment by chfritz** [comment]
:+1:

**Comment by chfritz** [comment]
Please try the new version I just published (0.1.3). It should work now.

**Comment by chfritz** [comment]
Fxed in f7cf9e00b8947b5dfe9702eb772868068e1f3eb3.

**Comment by aneilbaboo** [comment]
Not quite working as expected:

![](http://g.recordit.co/YPeF3uC8nJ.gif)

**Comment by chfritz** [comment]
atom.io doesn't support indentation of less then the set indentation depth (usually two spaces). So if you really want a single space indentation just for comments, then I think you'll be on your own creating using a different logic (not atom.io's indentation logic).

On the last line, closing the comment, I can go either way.
