### ISSUE TITLE
in C++ "for" loops without curly brackets the next line is not properly indented

### ISSUE THREAD

**Issue by AdrianTM** [chfritz/atom-sane-indentation#21]
Loops need brackets (at least in my editor) otherwise the next line is not indented properly (will be the same level as "for" line), it's probably the same logic for "if", I tried to look in config but I could not figure it out why is not working.

**Comment by chfritz** [comment]
Hi @AdrianTM , thanks for reporting this! I've been able to reproduce this. It's working for `if`, but i'll also add the config for `for`.

**Comment by chfritz** [comment]
Nevermind, I *wasn't* able to reproduce this. When I thought I had, I had a syntax error somewhere else that broke the tree-sitter parser:

```c++
  for (int i; i < 10; i++)
    dothis();

  for (notvalid_syntax)
  dothis();
```

**Comment by chfritz** [comment]
Could you show me the example you used? I'm inclined to close this as not reproducible, but it's always possible that there is a valid case I haven't considered.

**Comment by AdrianTM** [comment]
This doesn't work, it doesn't recognize range-based expressions:
```c++
for (auto i : container)
    dothis();
```

**Comment by chfritz** [comment]
Thanks. Yes, tree-sitter reports this as a `for_range_loop`, rather than a `for_statement`, like all the other for-loops. I've added that to our config in eb95f51022e02c2f22db7b2a326690ad425ff8bc and pushed a new version (1.1.6). It should work once you upgrade the package.
